export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST"
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS"
export const REVIEW_CREATE_FAIL    = "REVIEW_CREATE_FAIL"
export const REVIEW_CREATE_RESET   = "REVIEW_CREATE_RESET"

export const REVIEW_PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const REVIEW_PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const REVIEW_PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

